language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

sudo: false

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt coverageAggregate
  
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coveralls
